kind: ingress
items:
  - metadata:
      namespace: test-namespace
      name: test-ingress-1
    spec:
      rules:
        - host: www.example.org
          http:
            paths:
              - path: /
                backend:
                  serviceName: test-service
                  servicePort: 80
